apiVersion: v2
name: nexus
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: secure_ingress
    version: 1.0.0
    repository: https://nexus-craigmiller160.ddns.net/repository/helm-private