deployment:
  name: nexus
  volumeNames:
    nexusDataVolume: nexus-data-volume
    tlsVolume: nexus-tls-volume
    jettyHttpsVolume: nexus-jetty-https-volume
    nexusPropsVolume: nexus-properties-volume
pvc:
  name: nexus-data-pvc
certificate:
  name: nexus-internal-certificate
secrets:
  keystorePassword: nexus-keystore-password