apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.deployment.name }}-internal-certificate
spec:
  isCA: true
  commonName: {{ .Values.deployment.name }}
  secretName: {{ .Values.deployment.name }}-internal-certificate
  subject:
    organizations:
      - "Craig Miller"
    organizationalUnits:
      - Nexus
    countries:
      - US
    states:
      - FL
  dnsNames:
    - nexus-docker.infra-prod
    - nexus-standard.infra-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: craigmiller160-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: nexus-keystore-password
        key: password