apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      initContainers:
        - name: setup
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - |
              chown -R 200:200 /nexus-data
          volumeMounts:
            - mountPath: /nexus-data
              name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
      containers:
        - name: nexus
          image: sonatype/nexus3:3.41.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 8083
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 20
            httpGet:
              port: 8081
              path: /
          livenessProbe:
            initialDelaySeconds: 250
            periodSeconds: 300
            httpGet:
              port: 8081
              path: /
          volumeMounts:
            - mountPath: /nexus-data
              name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
            - mountPath: /tls
              name: {{ .Values.deployment.volumeNames.tlsVolume }}
            - mountPath: /opt/sonatype/nexus/etc/jetty/jetty-https.xml
              name: {{ .Values.deployment.volumeNames.jettyHttpsVolume }}
              subPath: jetty-https.xml
            - name: {{ .Values.deployment.volumeNames.nexusPropsVolume }}
              mountPath: /opt/sonatype/nexus/etc/nexus.properties
              subPath: nexus.properties
          env:
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.secrets.keystorePassword }}
      volumes:
        - name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: {{ .Values.deployment.volumeNames.tlsVolume }}
          secret:
            secretName: {{ .Values.certificate.name }}
        - name: {{ .Values.deployment.volumeNames.nexusPropsVolume }}
          configMap:
            name: nexus-properties-configmap
        - name: {{ .Values.deployment.volumeNames.jettyHttpsVolume }}
          configMap:
            name: nexus-jetty-https-configmap