apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-nginx-passthrough-cert
  namespace: infra-prod
spec:
  isCA: true
  commonName: docker-nginx-passthrough-cert
  secretName: docker-nginx-passthrough-cert
  subject:
    organizations:
      - "Craig Miller"
    organizationalUnits:
      - Nexus
    countries:
      - US
  dnsNames:
    - docker-nginx-passthrough.infra-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: craigmiller160-selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io