apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.docker_passthrough.name }}
spec:
  type: ClusterIP
  selector:
    app: docker-nginx-passthrough
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP