apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      initContainers:
        - name: setup
          image: busybox:1.28
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - chown -R 200:200 /nexus-data
          volumeMounts:
            - mountPath: /nexus-data
              name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
      containers:
        - name: nexus
          image: sonatype/nexus3:3.41.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            - containerPort: 8083
          volumeMounts:
            - mountPath: /nexus-data
              name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
      volumes:
        - name: {{ .Values.deployment.volumeNames.nexusDataVolume }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - name: standard
      port: 8081
      targetPort: 8081
    - name: docker-http
      port: 8083
      targetPort: 8083