apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: craig-hostpath
  resources:
    requests:
      storage: 100Gi