apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-standard
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-docker
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: 80
      targetPort: 8083