apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - name: standard
      port: 8081
      targetPort: 8081
    - name: docker-http
      port: 8083
      targetPort: 8083